# Generated by Django 3.2.3 on 2021-05-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('empID', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('aadharNumber', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('branch', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('date_joined', models.DateField()),
                ('dob', models.DateField()),
                ('image', models.TextField()),
            ],
        ),
    ]
