# Generated by Django 3.2.3 on 2021-05-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='isActive',
            field=models.CharField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='employee',
            name='empID',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.TextField(default='https://cdn.pixabay.com/photo/2015/03/04/22/35/head-659652_960_720.png'),
        ),
    ]
