# Generated by Django 3.2.3 on 2021-05-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210517_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='image',
            new_name='profileImage',
        ),
        migrations.AddField(
            model_name='employee',
            name='IFSCCode',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='aadharBackImage',
            field=models.TextField(default='https://cdn.pixabay.com/photo/2015/03/04/22/35/head-659652_960_720.png'),
        ),
        migrations.AddField(
            model_name='employee',
            name='aadharFrontImage',
            field=models.TextField(default='https://cdn.pixabay.com/photo/2015/03/04/22/35/head-659652_960_720.png'),
        ),
        migrations.AddField(
            model_name='employee',
            name='accountNumber',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='bankname',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='pancard',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='pancardImage',
            field=models.TextField(default='https://cdn.pixabay.com/photo/2015/03/04/22/35/head-659652_960_720.png'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passbookImage',
            field=models.TextField(default='https://cdn.pixabay.com/photo/2015/03/04/22/35/head-659652_960_720.png'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='empID',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(default='', max_length=50),
        ),
    ]
