# Generated by Django 3.2.3 on 2021-05-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210519_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='aadharBackImage',
            field=models.TextField(default='https://blog.qburst.com/wp-content/uploads/2019/10/01_aadhar_front_side_original.jpg'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='aadharFrontImage',
            field=models.TextField(default='https://blog.qburst.com/wp-content/uploads/2019/10/01_aadhar_front_side_original.jpg'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pancardImage',
            field=models.TextField(default='https://yourspj.files.wordpress.com/2011/06/fake-pan-card_yourspj.jpg'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passbookImage',
            field=models.TextField(default='https://qph.fs.quoracdn.net/main-qimg-14d1798dac81721780d1404cb5620251'),
        ),
    ]
