# Generated by Django 3.2.3 on 2021-06-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20210519_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='aadharBackImage',
            field=models.FileField(upload_to='media/aadhar/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='aadharFrontImage',
            field=models.FileField(upload_to='media/aadhar/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pancardImage',
            field=models.FileField(upload_to='media/pancard/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passbookImage',
            field=models.FileField(upload_to='media/bankAccount/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profileImage',
            field=models.FileField(upload_to='media/profile/'),
        ),
    ]
