# Generated by Django 3.2.3 on 2021-06-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20210601_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='aadharBackImage',
            field=models.ImageField(upload_to='media/aadhar/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='aadharFrontImage',
            field=models.ImageField(upload_to='media/aadhar/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pancardImage',
            field=models.ImageField(upload_to='media/pancard/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passbookImage',
            field=models.ImageField(upload_to='media/bankAccount/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profileImage',
            field=models.ImageField(upload_to='media/profile/'),
        ),
    ]
