# Generated by Django 3.2.3 on 2021-05-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passowrd',
            new_name='password',
        ),
    ]
