# Generated by Django 3.2.3 on 2021-05-25 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_passowrd_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='token',
            new_name='accessToken',
        ),
    ]
