# Generated by Django 3.2.3 on 2021-05-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empID', models.CharField(max_length=20, unique=True)),
                ('daydate', models.DateTimeField(auto_now_add=True)),
                ('timing_in', models.TimeField(auto_now_add=True)),
                ('timing_out', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
