# Generated by Django 3.2.3 on 2021-05-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='daydate',
            field=models.DateTimeField(),
        ),
    ]
