# Generated by Django 3.2.3 on 2021-05-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20210521_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='timing_in',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='timing_out',
            field=models.CharField(default='', max_length=12),
        ),
    ]
