# Generated by Django 3.2.3 on 2021-05-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_alter_attendance_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='daydate',
            field=models.DateField(),
        ),
    ]
