# Generated by Django 3.2.3 on 2021-05-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_alter_attendance_daydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='daydate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
