# Generated by Django 3.2.3 on 2021-06-01 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20210601_0943'),
        ('attendance', '0020_alter_attendance_daydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='empID',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='employee.employee', to_field='empID'),
        ),
    ]
