# Generated by Django 3.2.3 on 2021-06-03 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20210602_0446'),
        ('attendance', '0021_alter_attendance_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='empID',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee', to_field='empID'),
        ),
    ]
